PROMPT CREATE TABLE dataintegra.tbl_dti_paciente
CREATE TABLE dataintegra.tbl_dti_paciente (
  cd_dti_paciente       NUMBER(20,0)   NULL,
  tp_status             VARCHAR2(200)  NULL,
  ds_erro               VARCHAR2(4000) NULL,
  dt_gerado             DATE           NULL,
  tp_registro           VARCHAR2(3)    NULL,
  tp_fluxo              VARCHAR2(1)    NULL,
  tp_movimento          VARCHAR2(1)    NULL,
  cd_multi_empresa      NUMBER(4,0)    NULL,
  cd_registro_principal NUMBER(20,0)   NULL,
  cd_registro_pai       NUMBER(20,0)   NULL,
  cd_registro_filho     VARCHAR2(4000) NULL,
  tp_pessoa             VARCHAR2(1)    NULL,
  cd_paciente           VARCHAR2(100)  NULL,
  nm_pessoa             VARCHAR2(200)  NULL,
  nm_sobrenome          VARCHAR2(200)  NULL,
  dt_nascimento         VARCHAR2(200)  NULL,
  tp_sexo               VARCHAR2(1)    NULL,
  ds_endereco           VARCHAR2(100)  NULL,
  nr_endereco           VARCHAR2(8)    NULL,
  nm_cidade             VARCHAR2(40)   NULL,
  nr_cep                VARCHAR2(10)   NULL,
  cd_uf                 VARCHAR2(2)    NULL,
  nr_telefone           VARCHAR2(40)   NULL,
  nr_celular            VARCHAR2(40)   NULL,
  cd_convenio           VARCHAR2(30)   NULL,
  ds_email              VARCHAR2(200)  NULL,
  cd_paciente_integra   VARCHAR2(50)   NULL
)
/